### ISSUE TITLE
links don't work

### ISSUE THREAD

**Issue by lyubar** [GoInterject/GoInterject.github.io#8]
File: [wGetStarted/Creating-with-INTERJECT.md](https://docs.gointerject.com/wGetStarted/Creating-with-INTERJECT.html)

**Comment by Axedentist** [comment]
Issue was due to file name changes to line up with naming best practices but missed a couple links that pointed to those pages. The issue should be fixed on this page and I searched for the same bad link in other pages and did a bulk replace. Issue should be fixed on this page as well as others now. Changes pushed to patch-1 branch.

**Comment by derekolson09** [comment]
This issue has been addressed.
